apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-logger
  template:
    metadata:
      labels:
        app: custom-logger
    spec:
      containers:
        - name: custom-logger
          image: PROJECT/IMAGE1